### ISSUE TITLE
Workshop proceedings missing / DOI links do not resolve

### ISSUE THREAD

**Issue by matthiasch** [InsightSoftwareConsortium/InsightJournal#111]
Greetings,

It appears that quite some publications went missing. I noticed that one of my own publications, which was part of the **MICCAI 2014 Workshop on Image-Guided Adaptive Radiation Therapy (IGART)** is not available anymore.

The handle and DOI links

http://hdl.handle.net/10380/3491
http://dx.doi.org/10.54294/lgcmkl

lead to the following error message:
`
ipfs resolve -r /ipfs/bafybeigcuragxgowyanltzo4t5wmzwdvlv5qxkyme3rdlfpb4nvdqp33pe/browse/publication/938: no link named "938" under Qme5S1jdJsrgd6GS3DSX41n1ZFbUeZhkUQa5kG6qQgnUqF
`

They are still listed/referenced in the file [data/issues/383.json](https://github.com/InsightSoftwareConsortium/InsightJournal/blob/master/data/issues/383.json):
>   ...
    "issue": {
    "date": "2014",
    "issue_id": 383,
    "name": "MICCAI 2014 Workshop: Image-Guided Adaptive Radiation Therapy (IGART)",
    "publications": [925,937,938,939,940,941,942,945,946,947,948,958],
    "short_description": "The workshop aims at presenting leading edge applications of medical image processing in the field of radiotherapy. The workshop provides an invaluable opportunity to present and discuss recent and preliminary research in this exciting field, in addition to providing a good forum to get constructive feedback from fellow researchers on more developed pieces of work."
    ...

They are also not listed on the website anymore, when I use, for instance, the search functionality or browse issues by year. Other workshop proceedings seem to be affected by this issue as well.

I hope this issue can get resolved somehow. Thank you,
Matthias

**Comment by phcerdan** [comment]
Thanks for the report @matthiasch , I can reproduce it.
We have the 938/metadata.json there indeed.
Maybe a problem uploading to pinata @thewtex?

**Comment by thewtex** [comment]
@matthiasch thanks for the report!

A previous merge did not merge as expected -- this will correct it: https://github.com/InsightSoftwareConsortium/InsightJournal/pull/114

**Comment by phcerdan** [comment]
Fixed in #114

**Comment by matthiasch** [comment]
Thank you @thewtex  and @phcerdan for making the publications available again. There is still an issue with the order in which the authors appear. It's in reverse order. All publications seem to be affected. Should I open a new issue?

**Comment by thewtex** [comment]
@matthiasch yes, please create a new issue :pray:
